name: Dotnet
on: [workflow_dispatch, push]
jobs:
  upload_dotnet_tool_cache:
    runs-on: ubuntu-20.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Dotnet 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Setup Dotnet 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf dotnet_tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-actions-cached
          path: ${{runner.tool_cache}}/dotnet_tool_cache.tar.gz
